apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: coin-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: rafaelor20/coin_manager_node:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-env
