services:
  postgres:
    image: postgres:17-alpine
    pull_policy: if_not_present
    container_name: coin_manager_db
    restart: always
    ports:
      - 5433:5432
    env_file:
      - back-end/.env.development
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d coin_manager"]
      interval: 5s
      timeout: 5s
      retries: 5

  node:
    container_name: coin_manager_backend
    build: ./back-end
    restart: always
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - back-end/.env.development

  react:
    container_name: coin_manager_react
    build: ./front-end
    volumes:
      - react-volume:/var/www/html

  nginx:
    container_name: coin_manager_nginx
    build: ./nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - postgres
      - node
      - react

volumes:
  postgres-volume:
  react-volume:
