name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: avantibootcamp.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}


      - name: Build and push backend
        run: |
          docker build -t avantibootcamp.azurecr.io/coin-manager-backend ./back-end
          docker push avantibootcamp.azurecr.io/coin-manager-backend

      - name: Build and push frontend (nginx)
        run: |
          docker build -t avantibootcamp.azurecr.io/coin-manager-frontend ./nginx
          docker push avantibootcamp.azurecr.io/coin-manager-frontend

      - name: Debug SSH Variables
        run: |
          if [ -z "${{ secrets.AZURE_VM_HOST }}" ]; then echo "AZURE_VM_IP est치 vazio!"; else echo "AZURE_VM_IP definido."; fi
          if [ -z "${{ secrets.AZURE_VM_USER }}" ]; then echo "AZURE_VM_USER est치 vazio!"; else echo "AZURE_VM_USER definido."; fi
          if [ -z "${{ secrets.AZURE_SSH_PRIVATE_KEY }}" ]; then echo "AZURE_VM_SSH_KEY est치 vazio!"; else echo "AZURE_VM_SSH_KEY definido."; fi
        
 
      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 20.120.242.63
          username: superuser
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Deploying to Azure VM..."

            if ! command -v docker-compose &> /dev/null; then
                sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
            fi

            docker --version
            docker-compose --version

            echo "Logando no ACR..."
            echo "${{ secrets.AZURE_ACR_PASSWORD }}" | sudo docker login avantibootcamp.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

            echo "Atualizando c칩digo fonte..."
            sudo rm -rf /opt/coin-manager
            sudo git clone https://${{ secrets.GH_DEPLOY_TOKEN }}@github.com/elizeurjr/coin-manager-fullstack.git /opt/coin-manager
            cd /opt/coin-manager

            echo "Atualizando imagens..."
            sudo docker-compose pull
            sudo docker pull avantibootcamp.azurecr.io/coin-manager-backend
            sudo docker pull avantibootcamp.azurecr.io/coin-manager-frontend

            echo "Subindo containers..."
            sudo docker-compose -f /opt/coin-manager/docker-compose.yml up -d

